spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: QUESTION-SERVICE
        uri: lb://QUESTION-SERVICE
        predicates:
        - Path=/question/**
        
      - id: QUIZ-SERVICE
        uri: lb://QUIZ-SERVICE
        predicates:
        - Path=/quiz/**

server:
  port: 8085
